baseURL = 'https://dawsondev.github.io/'
languageCode = 'en-us'
title = 'Oliver Dawson'
theme = ['hugo-embed-pdf-shortcode','hugo-theme-m10c']
enableInlineShortcodes = true
publishDir = 'public'

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Misc"
    url = "/misc/"
    weight = 3

[params]
  subtitle = 'The Best Widgets on Earth'
  author = 'Oliver Dawson'
  description = 'description test'
  favicon ='https://dawsondev.github.io/favicon.ico'
  avatar = '/dive_zenobia_cyprus.jpg'
  [params.contact]
    email = 'dawson_oliver@yahoo.com'
    phone ='1243243434'