baseURL = 'https://dawsondev.github.io/'
languageCode = 'en-us'
title = 'Oliver Dawson'
theme = ['hugo-theme-m10c']
publishDir = 'public'
paginate = 10
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/CV.pdf"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[params]
  subtitle = 'DawsonDev'
  author = 'Oliver Dawson'
  description = 'Welcome to my website!'
  favicon ='https://dawsondev.github.io/favicon.ico'
  avatar = '/dive_zenobia_cyprus.jpg'
  [params.footer]
       text = "© Oliver Dawson 2024"
    [[params.socialIcons]]
       icon = "fab fa-github-square"
       title = "Github"
       url = "https://github.com/dawsondev"
    [[params.socialIcons]]
       icon = "fab fa-linkedin"
       title = "LinkedIn"
    url = "https://www.linkedin.com/in/oliver-dawson-00202a208"
    [[params.socialIcons]]
       icon = "fas fa-envelope"
       title = "E-mail"
       url = "mailto:dawson_oliver@yahoo.com"

